# Generated by Django 5.2.7 on 2025-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(default='2025-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='grau_autismo',
            field=models.CharField(choices=[('1', 'Nível 1 - Leve'), ('2', 'Nível 2 - Moderado'), ('3', 'Nível 3 - Severo')], default='1', max_length=1, verbose_name='Grau de Autismo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tem_laudo',
            field=models.BooleanField(default=False, verbose_name='Possui laudo médico?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
    ]
