# Generated by Django 5.2.7 on 2025-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='info_text',
            field=models.TextField(blank=True, help_text="Este texto aparecerá quando o utilizador clicar no botão 'i'.", null=True, verbose_name='Texto de Informação (Ajuda)'),
        ),
    ]
