# Generated by Django 5.2.7 on 2026-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tip_high',
            field=models.TextField(blank=True, verbose_name='Dica para nota alta (8-10)'),
        ),
        migrations.AddField(
            model_name='section',
            name='tip_low',
            field=models.TextField(blank=True, verbose_name='Dica para nota baixa (0-3)'),
        ),
        migrations.AddField(
            model_name='section',
            name='tip_medium',
            field=models.TextField(blank=True, verbose_name='Dica para nota média (4-7)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sectionresult',
            name='score',
            field=models.IntegerField(verbose_name='Pontuação'),
        ),
    ]
