# Generated by Django 5.2.7 on 2026-01-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_section_tip_high_section_tip_low_section_tip_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tip_high',
            field=models.TextField(blank=True, verbose_name='Dica para nota alta (7-10)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tip_low',
            field=models.TextField(blank=True, verbose_name='Dica para nota baixa (0-4)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tip_medium',
            field=models.TextField(blank=True, verbose_name='Dica para nota média (5-6)'),
        ),
    ]
